### ISSUE TITLE
Revert to bionic

### ISSUE THREAD

**Issue by masimun** [AndrewMarchukov/insurgency-sandstorm-server-dockerize#1]
https://github.com/AndrewMarchukov/insurgency-sandstorm-server-dockerize/blob/69245353c05bc3ff35da6afee6c675980ed9c1d0/Dockerfile#L1

https://stackoverflow.com/questions/63061908/docker-ubuntu-picking-wrong-directory

Got an error in latest ubuntu -> Fix: Change first line in dockerfile to FROM ubuntu:bionic

**Comment by AndrewMarchukov** [comment]
i don't have any error: https://github.com/AndrewMarchukov/insurgency-sandstorm-server-dockerize/runs/2579690564?check_suite_focus=true
github build image fine
you build with i386?
