### ISSUE TITLE
Conditional Release?

### ISSUE THREAD

**Issue by telnetdoogie** [AndrewMarchukov/insurgency-sandstorm-server-dockerize#7]
Intentional I know; in the readme it mentions releasing daily.

When using something like watchtower, it detects the new daily build of the docker image (with a new digest) and downloads and recreates the container... when in reality nothing has changed...

This could be resolved / relieved by ignoring this specific container from watchtower, but then if something DID change it wouldn't be updated (which is super desirable)

...any way we can make the daily build conditional on a recent change, or just triggered by pull requests versus just scheduled?

**Comment by dcaillouet** [comment]
You should be able to remove the scheduled section in your github action.

**Comment by telnetdoogie** [comment]
https://steamcommunity.com/app/346110/discussions/0/530646715636738547/

I think you can check the patch version of the app as noted in this thread and then perhaps end the script for autoupdate if it's the same version as prior?

**Comment by telnetdoogie** [comment]
I saw your changes @AndrewMarchukov .... I like what you've done there... Based on what I see, I would expect to see a new docker image pushed on the next scheduled action, and then the following day (assuming no change to the steam app version) no new image. Is that what you're expecting as well?

**Comment by dcaillouet** [comment]
@AndrewMarchukov  It looks like the variables attempting to be assigned are failing.   Try `echo "variableName=${cat sandstorm.version}" >> $GITHUB_ENV if it is in fact incorrect.

**Comment by AndrewMarchukov** [comment]
everything is okay, except api.steamcmd.net is dead and i don't know how get insurgency server version without it

**Comment by telnetdoogie** [comment]
https://github.com/AndrewMarchukov/insurgency-sandstorm-server-dockerize/blob/35c33c515bb1fe5ff5a2cd17164be33021f6ce0a/.github/workflows/docker-image.yml#L19

:clap:

**Comment by telnetdoogie** [comment]
Nice job @AndrewMarchukov !!
